os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"

before_script:
  - git submodule update --init --recursive
  - bash build.sh --all --skip-tests --product
  - bash build/bin/start-xatkit-linux.sh

script:

after_success:

notifications:
  email: no    