os: linux
dist: trusty
language: java
jdk: oraclejdk8

env:
  - XATKIT_DEV=$TRAVIS_BUILD_DIR XATKIT=$TRAVIS_BUILD_DIR/build
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - nvm install node # "node" is an alias for the latest version. we may need to install a specific version
  - travis_wait 30 bash .utils/build_xatkit.sh
before_script:
  - bash .utils/start_xatkit.sh
  - cd tests/greetings
  - npm install
  - sleep 15
script:
  - npm test

notifications:
  email: no
